# comment 不能用``
# 字段名 表名 都用飘号 其他不能用飘号

# 管理员
CREATE TABLE IF NOT EXISTS `admin_user` (
  `user_id` VARCHAR(32) NOT NULL,
  `user_name` VARCHAR(64) NOT NULL COMMENT "用户名",
  `user_password` VARCHAR(64) NOT NULL COMMENT "用户密码",
  `ec_salt` VARCHAR(64) COMMENT "加密密码",
  `user_portrait` VARCHAR(64) COMMENT "用户头像",
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT "创建时间",
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT "修改时间",
  PRIMARY KEY (`user_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT "管理员";


# 新闻中心 news_center
CREATE TABLE IF NOT EXISTS `news_center` (
  `news_id` VARCHAR(32) NOT NULL,
  `news_title` VARCHAR(64) NOT NULL COMMENT "标题",
  `news_author` VARCHAR(32) NOT NULL DEFAULT "润捷" COMMENT "作者", 
  `news_content` LONGTEXT NOT NULL COMMENT "详细内容",
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT "创建时间",
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT "修改时间",
  PRIMARY KEY (`news_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT "新闻中心";


# 服务项目
CREATE TABLE IF NOT EXISTS `service_items`(
  `service_id` VARCHAR(32) NOT NULL,
  `service_name` VARCHAR(32) NOT NULL COMMENT "服务名字",  
  `service_content` LONGTEXT NOT NULL COMMENT "服务内容描述",
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT "创建时间",
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT "修改时间",
  PRIMARY KEY (`service_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT "服务项目";


# 体系认证项目
CREATE TABLE IF NOT EXISTS `certi_items`(
  `certi_id` VARCHAR(32) NOT NULL,
  `certi_name` VARCHAR(64) NOT NULL COMMENT "认证名称",
  `cert_mainpic` VARCHAR(64) COMMENT "认证主图",
  `certi_content` LONGTEXT NOT NULL COMMENT "认证内容描述",
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT "创建时间",
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT "修改时间",
  PRIMARY KEY (`certi_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT "体系认证项目";

# 证书样本
CREATE TABLE IF NOT EXISTS `certi_sample`(
  `sample_id` VARCHAR(32) NOT NULL,
  `sample_name` VARCHAR(64) NOT NULL COMMENT "证书名称",
  `sample_mainpic` VARCHAR(64) COMMENT "证书主图",
  `sample_content` LONGTEXT NOT NULL COMMENT "证书内容描述",
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT "创建时间",
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT "修改时间",
  PRIMARY KEY (`sample_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT "证书样本";
