spring:  
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 
    url: jdbc:mysql://116.62.240.193:3306/consult?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
  jpa:
    show-sql:true
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
server: 
  max-http-header-size: 10240000
  tomcat: 
    max-http-header-size: 10240000
    max-http-post-size: 10240000
  servlet: 
    context-path: /consult  
logging:
  pattern:
    console: "%d - %msg%n"
  path: d:/
system:
  #filepath: /vdb1/xxx/vue/resources
  filepath: F:/springboot_consult/src/main/resources/static/article/
  urlpath: http://localhost:8080/consult/article/